//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECSalesEntities2 : DbContext
    {
        public ECSalesEntities2()
            : base("name=ECSalesEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblAddedProduct> TblAddedProducts { get; set; }
        public virtual DbSet<TblCategory> TblCategories { get; set; }
        public virtual DbSet<TblRequestedIncubation> TblRequestedIncubations { get; set; }
        public virtual DbSet<TblUserComment> TblUserComments { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productHistory> productHistories { get; set; }
    }
}
