//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productHistory
    {
        public int ID { get; set; }
        public string Ename { get; set; }
        public string Aname { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsService { get; set; }
        public Nullable<int> status { get; set; }
        public string OldData { get; set; }
        public string AdminComment { get; set; }
    
        public virtual TblCategory TblCategory { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
