//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRequestedIncubation
    {
        public int ID { get; set; }
        public Nullable<int> RequestedUser { get; set; }
        public string RequestedDescription { get; set; }
        public string AttchedFile { get; set; }
        public Nullable<int> Status { get; set; }
        public string AdminComment { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
